config:
  validation: true
  warningsAsErrors: true

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  TooManyFunctions:
    ignoreAnnotatedFunctions:
      - Preview

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
  TopLevelPropertyNaming:
    constantPattern: '[A-Z](?:[A-Za-z0-9]*|[A-Z0-9_]*)'

style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateFunction:
    ignoreAnnotated:
      - Preview

Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableNestingDepth:
    active: false
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: true
  CompositionLocalNaming:
    active: true
  ConditionHoist:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentSlotReused:
    active: true
  ContentTrailingLambda:
    active: true
  DefaultsVisibility:
    active: true
  InvalidReadOnlyComposable:
    active: true
  LambdaParameterEventTrailing:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  Material2:
    active: false
  MissingNonRestartableComposable:
    active: true
  MissingReadOnlyComposable:
    active: true
  ModifierClickableOrder:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ParameterNaming:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewNaming:
    active: false
  PreviewPublic:
    active: true
  RememberContentMissing:
    active: true
  RememberMissing:
    active: true
  StaleRememberUpdatedStateInRemember:
    active: true
  StateParam:
    active: true
  UnnecessaryComposable:
    active: true
  UnnecessaryLaunchedEffect:
    active: true
  UnstableCollections:
    active: false
  VarsWithoutStateBacking:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
